import JobRouter from "../modules/job/job.route.js";
import StatsRouter from "../modules/dashboard/dashboard.route.js";
import UniversityRouter from "../modules/university/university.route.js";
import CompanyRouter from "../modules/company/company.route.js";
import ApplicationRouter from "../modules/application/application.route.js";
import CollegeRouter from "../modules/college/college.route.js";
import BranchRouter from "../modules/branch/branch.route.js";
import DegreeRouter from "../modules/degree/degree.route.js";
import DegreeMasterRoutes from "../modules/degree/degreemaster.route.js";
import StudentRouter from "../modules/student/student.route.js";
import CvTemplateRouter from "../modules/student/cvTemplate.route.js";
import TPORouter from "../modules/tpo/tpo.route.js";
import authRouter from "../modules/auth/auth.route.js";
import LoginRouter from "../modules/auth/login.route.js";
import userRouter from "../modules/auth/user.route.js";
import DropdownRouter from "../modules/dropdown/dropdown.route.js";
import ExamRouter from "../modules/exam/exam.route.js";
import PaperRouter from "../modules/exam/paper.route.js";
import ContactRouter from "../modules/contact/contact.route.js";
import PaymentRouter from "../modules/subscription/payment.route.js";
import ExamPaymentRouter from "../modules/subscription/exampayment.route.js";
import RoundRouter from "../modules/interview/round.route.js";
import InterviewRouter from "../modules/interview/interview.route.js";
import RecruitmentSubscriptionRouter from "../modules/subscription/subscription.route.js";
import { getActivePlans } from "../modules/subscription/subscription.controller.js";
import PreparationRouter from "../modules/preparation/preparation.route.js";
import UploadRouter from "../modules/upload/upload.route.js";

import { authenticateUser } from "../middleware/authMiddleware.js";

export const setupRoutes = (app) => {
  app.use("/api/jobs", authenticateUser, JobRouter);
  app.use("/api/stats", authenticateUser, StatsRouter);
  app.use("/api/contact", ContactRouter);
  app.use("/api/university", UniversityRouter);
  app.use("/api/dropdown", DropdownRouter);
  app.use("/api/order", authenticateUser, PaymentRouter);
  app.use("/api/payment", authenticateUser, PaymentRouter);
  app.use("/api/aiexam", authenticateUser, ExamPaymentRouter);
  app.use("/api/exam", authenticateUser, ExamRouter);
  app.use("/api/paper", authenticateUser, PaperRouter);
  app.use("/api/rounds", authenticateUser, RoundRouter);
  app.use("/api/interviews", authenticateUser, InterviewRouter);
  app.get("/api/recruitment-subscription/plans/active", getActivePlans);
  app.use("/api/recruitment-subscription", authenticateUser, RecruitmentSubscriptionRouter);
  app.use("/api/preparation", authenticateUser, PreparationRouter);
  app.use("/api/upload", UploadRouter);
  app.use("/api/company", CompanyRouter);
  app.use("/api/application", authenticateUser, ApplicationRouter);
  app.use("/api/college", CollegeRouter);
  app.use("/api/branch", authenticateUser, BranchRouter);
  app.use("/api/degree", authenticateUser, DegreeRouter);
  app.use("/api/degreeMaster", DegreeMasterRoutes);
  app.use("/api/student", authenticateUser, StudentRouter);
  app.use("/api/cv-templates", authenticateUser, CvTemplateRouter);
  app.use("/api/register", StudentRouter);
  app.use("/api/tpo", authenticateUser, TPORouter);
  app.use("/api/auth", authRouter);
  app.use("/api/login", LoginRouter);
  app.use("/api/logout", LoginRouter);
  app.use("/api/users", authenticateUser, userRouter);
};
