import mongoose from "mongoose";

const EducationSchema = new mongoose.Schema({
  institution: { type: String, required: true },
  degree: { type: String, required: true },
  fieldOfStudy: { type: String },
  startYear: { type: String },
  endYear: { type: String },
  score: { type: String }, // CGPA or Percentage
});

const ProjectSchema = new mongoose.Schema({
  title: { type: String, required: true },
  description: { type: String, required: true },
  technologies: [String],
  link: { type: String },
});

const ExperienceSchema = new mongoose.Schema({
  company: { type: String },
  role: { type: String },
  description: { type: String },
  startDate: { type: String },
  endDate: { type: String },
});

const ResumeSchema = new mongoose.Schema(
  {
    student_id: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "tbl_student",
      required: true,
      unique: true,
    },
    punch_line: { type: String }, // Short title e.g. "Full Stack Developer"
    linkedin: { type: String },
    github: { type: String },
    portfolio: { type: String },
    education: [EducationSchema],
    skills: [String],
    projects: [ProjectSchema],
    experience: [ExperienceSchema], // Internships / Jobs
    languages: [String],
    certifications: [String],
    selected_template: {
      type: String,
      default: "modern",
    },
    selected_template_id: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "tbl_cv_template",
    },
    font_family: {
      type: String,
      default: "Inter",
    },
    color_theme: {
      type: String,
      default: "#3730a3",
    },
    layout_columns: {
      type: String,
      default: "two_column_left",
    },
    page_margin: {
      type: String,
      default: "medium",
    },
    ai_compiled_html: { type: String },
    ai_compiled_css: { type: String },
    // Store 5 professional summary/profile variations generated by OpenAI
    ai_summaries: {
      type: [String],
      default: [],
    },
    chosen_summary: { type: String },
  },
  { timestamps: true }
);

export default mongoose.models.tbl_resume || mongoose.model("tbl_resume", ResumeSchema);
